module TOP(clk,rst,next,pc,ins0,ins1,ins2,ins3,in0,in1,in2,in3,valid,in0_out,in1_out,in2_out,in3_out,valid_out_iqueue,
           ins0_out_D,ins1_out_D,ins2_out_D,ins3_out_D,valid_out_D,
           opcode_0,opcode_1,opcode_2,opcode_3,rs1_0,rs1_1,rs1_2,rs1_3,rs2_0,rs2_1,rs2_2,rs2_3,rd_0,rd_1,rd_2,rd_3,imm_0,imm_1,imm_2,imm_3,func7_0,func7_1,func7_2,func7_3,func3_0,func3_1,func3_2,func3_3,has_dest,is_branch,is_jump,is_jalr,is_load,is_store,valid_out_decode,
           rat_rs1_0,rat_rs1_1,rat_rs1_2,rat_rs1_3,rat_rs2_0,rat_rs2_1,rat_rs2_2,rat_rs2_3,rat_rd_0,rat_rd_1,rat_rd_2,rat_rd_3,prs1_0,prs1_1,prs1_2,prs1_3,prs2_0,prs2_1,prs2_2,prs2_3,old_prd_0,old_prd_1,old_prd_2,old_prd_3,rat_update_valid,rat_new_rd_0,rat_new_rd_1,rat_new_rd_2,rat_new_rd_3,rat_new_prd_0,rat_new_prd_1,rat_new_prd_2,rat_new_prd_3,fl_alloc_req,alloc_preg_0,alloc_preg_1,alloc_preg_2,alloc_preg_3,fl_stall,
           prs1_out_0,prs1_out_1,prs1_out_2,prs1_out_3,prs2_out_0,prs2_out_1,prs2_out_2,prs2_out_3,prd_out_0,prd_out_1,prd_out_2,prd_out_3,old_prd_out_0,old_prd_out_1,old_prd_out_2,old_prd_out_3,imm_out_0,imm_out_1,imm_out_2,imm_out_3,func7_out_0,func7_out_1,func7_out_2,func7_out_3,func3_out_0,func3_out_1,func3_out_2,func3_out_3,opcode_out_0,opcode_out_1,opcode_out_2,opcode_out_3,has_dest_out,is_branch_out,is_jump_out,is_jalr_out,is_load_out,is_store_out,valid_out_rename,stall,rob_free_valid,rob_free_preg_0,rob_free_preg_1,rob_free_preg_2,rob_free_preg_3,
           prs1_0_IQ,prs1_1_IQ,prs1_2_IQ,prs1_3_IQ,prs2_0_IQ,prs2_1_IQ,prs2_2_IQ,prs2_3_IQ,prd_0_IQ,prd_1_IQ,prd_2_IQ,prd_3_IQ,old_prd_0_IQ,old_prd_1_IQ,old_prd_2_IQ,old_prd_3_IQ,imm_0_IQ,imm_1_IQ,imm_2_IQ,imm_3_IQ,func7_0_IQ,func7_1_IQ,func7_2_IQ,func7_3_IQ,func3_0_IQ,func3_1_IQ,func3_2_IQ,func3_3_IQ,opcode_0_IQ,opcode_1_IQ,opcode_2_IQ,opcode_3_IQ,has_dest_IQ,is_branch_IQ,is_jump_IQ,is_jalr_IQ,is_load_IQ,is_store_IQ,valid_IQ,
           rd_out_0,rd_out_1,rd_out_2,rd_out_3,rd_0_IQ,rd_1_IQ,rd_2_IQ,rd_3_IQ,
           commit_valid,commit_rd_0,commit_rd_1,commit_rd_2,commit_rd_3,commit_prd_0,commit_prd_1,commit_prd_2,commit_prd_3,commit_data_0,commit_data_1,commit_data_2,commit_data_3,
           prf_ready,
           cdb_valid,cdb_tag_0,cdb_tag_1,cdb_tag_2,cdb_tag_3,cdb_data_0,cdb_data_1,cdb_data_2,cdb_data_3,
           rd_data_prs1_0,rd_data_prs1_1,rd_data_prs1_2,rd_data_prs1_3,rd_data_prs2_0,rd_data_prs2_1,rd_data_prs2_2,rd_data_prs2_3,
           issue_prs1_0,issue_prs1_1,issue_prs1_2,issue_prs1_3,issue_prs2_0,issue_prs2_1,issue_prs2_2,issue_prs2_3,issue_prd_0,issue_prd_1,issue_prd_2,issue_prd_3,issue_old_prd_0,issue_old_prd_1,issue_old_prd_2,issue_old_prd_3,issue_imm_0,issue_imm_1,issue_imm_2,issue_imm_3,issue_func7_0,issue_func7_1,issue_func7_2,issue_func7_3,issue_func3_0,issue_func3_1,issue_func3_2,issue_func3_3,issue_opcode_0,issue_opcode_1,issue_opcode_2,issue_opcode_3,issue_has_dest,issue_is_branch,issue_is_jump,issue_is_jalr,issue_valid,
           queue_full,queue_almost_full,
           rob_full,rob_almost_full,rob_store_commit,
           lsq_full,lsq_cdb_valid,lsq_cdb_tag,lsq_cdb_data,
           mem_addr,mem_wdata,mem_we,mem_re,mem_func3,rdata,ready,
           lsq_rd_prs1_0,lsq_rd_prs1_1,lsq_rd_prs1_2,lsq_rd_prs1_3,lsq_rd_prs2_0,lsq_rd_prs2_1,lsq_rd_prs2_2,lsq_rd_prs2_3,lsq_data_prs1_0,lsq_data_prs1_1,lsq_data_prs1_2,lsq_data_prs1_3,lsq_data_prs2_0,lsq_data_prs2_1,lsq_data_prs2_2,lsq_data_prs2_3,
           exec_data_prs1_0,exec_data_prs1_1,exec_data_prs1_2,exec_data_prs1_3,
           exec_data_prs2_0,exec_data_prs2_1,exec_data_prs2_2,exec_data_prs2_3,
           ex_prd_0,ex_prd_1,ex_prd_2,ex_prd_3,
           ex_imm_0,ex_imm_1,ex_imm_2,ex_imm_3,
           ex_func7_0,ex_func7_1,ex_func7_2,ex_func7_3,
           ex_func3_0,ex_func3_1,ex_func3_2,ex_func3_3,
           ex_opcode_0,ex_opcode_1,ex_opcode_2,ex_opcode_3,
           ex_has_dest,ex_is_branch,ex_is_jump,ex_is_jalr,ex_valid,
           ex_src1_data_0,ex_src1_data_1,ex_src1_data_2,ex_src1_data_3,
           ex_src2_data_0,ex_src2_data_1,ex_src2_data_2,ex_src2_data_3,
           alu_result_0,alu_result_1,alu_result_2,alu_result_3,
           alu_branch_taken_0,alu_branch_taken_1,alu_branch_taken_2,alu_branch_taken_3,
           alu_valid_0,alu_valid_1,alu_valid_2,alu_valid_3,
           alu_prd_0,alu_prd_1,alu_prd_2,alu_prd_3,
           alu_has_dest_0,alu_has_dest_1,alu_has_dest_2,alu_has_dest_3,
           wb_result_0,wb_result_1,wb_result_2,wb_result_3,
           wb_prd_0,wb_prd_1,wb_prd_2,wb_prd_3,
           wb_has_dest_0,wb_has_dest_1,wb_has_dest_2,wb_has_dest_3,
           wb_valid_0,wb_valid_1,wb_valid_2,wb_valid_3,
           wb_branch_taken_0,wb_branch_taken_1,wb_branch_taken_2,wb_branch_taken_3,
           wb_is_branch_0,wb_is_branch_1,wb_is_branch_2,wb_is_branch_3,
           lsq_store_ready,mispredicted,flush,is_branch_out_0,is_branch_out_1,is_branch_out_2,is_branch_out_3,alu3_stalled);
           
input clk,rst;
output [31:0] next,pc,ins0,ins1,ins2,ins3,in0,in1,in2,in3,in0_out,in1_out,in2_out,in3_out;
output [31:0] ins0_out_D,ins1_out_D,ins2_out_D,ins3_out_D,imm_0,imm_1,imm_2,imm_3,imm_out_0,imm_out_1,imm_out_2,imm_out_3;
output [31:0] imm_0_IQ,imm_1_IQ,imm_2_IQ,imm_3_IQ;
output [31:0] commit_data_0,commit_data_1,commit_data_2,commit_data_3,cdb_data_0,cdb_data_1,cdb_data_2,cdb_data_3;
output [31:0] rd_data_prs1_0,rd_data_prs1_1,rd_data_prs1_2,rd_data_prs1_3;
output [31:0] rd_data_prs2_0,rd_data_prs2_1,rd_data_prs2_2,rd_data_prs2_3;
output [31:0] issue_imm_0,issue_imm_1,issue_imm_2,issue_imm_3;
output [31:0] lsq_cdb_data,mem_addr,mem_wdata,rdata;
output [31:0] lsq_data_prs1_0,lsq_data_prs1_1,lsq_data_prs1_2,lsq_data_prs1_3;
output [31:0] lsq_data_prs2_0,lsq_data_prs2_1,lsq_data_prs2_2,lsq_data_prs2_3;
output [127:0] prf_ready;
output [4:0] rs1_0,rs1_1,rs1_2,rs1_3,rs2_0,rs2_1,rs2_2,rs2_3,rd_0,rd_1,rd_2,rd_3;
output [4:0] rat_rs1_0,rat_rs1_1,rat_rs1_2,rat_rs1_3,rat_rs2_0,rat_rs2_1,rat_rs2_2,rat_rs2_3,rat_rd_0,rat_rd_1,rat_rd_2,rat_rd_3,rat_new_rd_0,rat_new_rd_1,rat_new_rd_2,rat_new_rd_3;
output [4:0] rd_out_0,rd_out_1,rd_out_2,rd_out_3;
output [4:0] rd_0_IQ,rd_1_IQ,rd_2_IQ,rd_3_IQ;
output [4:0] commit_rd_0,commit_rd_1,commit_rd_2,commit_rd_3;
output [6:0] opcode_0,opcode_1,opcode_2,opcode_3,func7_0,func7_1,func7_2,func7_3;
output [6:0] prs1_0,prs1_1,prs1_2,prs1_3,prs2_0,prs2_1,prs2_2,prs2_3,old_prd_0,old_prd_1,old_prd_2,old_prd_3;
output [6:0] rat_new_prd_0,rat_new_prd_1,rat_new_prd_2,rat_new_prd_3,alloc_preg_0,alloc_preg_1,alloc_preg_2,alloc_preg_3;
output [6:0] prs1_out_0,prs1_out_1,prs1_out_2,prs1_out_3,prs2_out_0,prs2_out_1,prs2_out_2,prs2_out_3;
output [6:0] prd_out_0,prd_out_1,prd_out_2,prd_out_3,old_prd_out_0,old_prd_out_1,old_prd_out_2,old_prd_out_3;
output [6:0] func7_out_0,func7_out_1,func7_out_2,func7_out_3,opcode_out_0,opcode_out_1,opcode_out_2,opcode_out_3;
output [6:0] prs1_0_IQ,prs1_1_IQ,prs1_2_IQ,prs1_3_IQ,prs2_0_IQ,prs2_1_IQ,prs2_2_IQ,prs2_3_IQ;
output [6:0] prd_0_IQ,prd_1_IQ,prd_2_IQ,prd_3_IQ,old_prd_0_IQ,old_prd_1_IQ,old_prd_2_IQ,old_prd_3_IQ;
output [6:0] func7_0_IQ,func7_1_IQ,func7_2_IQ,func7_3_IQ;
output [6:0] opcode_0_IQ,opcode_1_IQ,opcode_2_IQ,opcode_3_IQ;
output [6:0] rob_free_preg_0,rob_free_preg_1,rob_free_preg_2,rob_free_preg_3,commit_prd_0,commit_prd_1,commit_prd_2,commit_prd_3;
output [6:0] cdb_tag_0,cdb_tag_1,cdb_tag_2,cdb_tag_3;
output [6:0] issue_prs1_0,issue_prs1_1,issue_prs1_2,issue_prs1_3;
output [6:0] issue_prs2_0,issue_prs2_1,issue_prs2_2,issue_prs2_3;
output [6:0] issue_prd_0,issue_prd_1,issue_prd_2,issue_prd_3;
output [6:0] issue_old_prd_0,issue_old_prd_1,issue_old_prd_2,issue_old_prd_3;
output [6:0] issue_func7_0,issue_func7_1,issue_func7_2,issue_func7_3;
output [6:0] issue_opcode_0,issue_opcode_1,issue_opcode_2,issue_opcode_3;
output [6:0] lsq_cdb_tag;
output [6:0] lsq_rd_prs1_0,lsq_rd_prs1_1,lsq_rd_prs1_2,lsq_rd_prs1_3;
output [6:0] lsq_rd_prs2_0,lsq_rd_prs2_1,lsq_rd_prs2_2,lsq_rd_prs2_3;
output [3:0] valid,valid_out_iqueue,valid_out_D,valid_out_decode,rat_update_valid,fl_alloc_req,valid_out_rename;
output [3:0] has_dest,is_branch,is_jump,is_jalr,is_load,is_store;
output [3:0] has_dest_out,is_branch_out,is_jump_out,is_jalr_out,is_load_out,is_store_out;
output [3:0] has_dest_IQ,is_branch_IQ,is_jump_IQ,is_jalr_IQ,is_load_IQ,is_store_IQ;
output [3:0] valid_IQ;
output [3:0] cdb_valid;
output [3:0] issue_has_dest,issue_is_branch,issue_is_jump,issue_is_jalr,issue_valid;
output [2:0] func3_0,func3_1,func3_2,func3_3,func3_out_0,func3_out_1,func3_out_2,func3_out_3;
output [2:0] func3_0_IQ,func3_1_IQ,func3_2_IQ,func3_3_IQ;
output [2:0] issue_func3_0,issue_func3_1,issue_func3_2,issue_func3_3,mem_func3;
output fl_stall,stall;
output [3:0] rob_free_valid,commit_valid;
output queue_full,queue_almost_full;
output rob_full,rob_almost_full,rob_store_commit;
output lsq_full,lsq_cdb_valid,mem_we,mem_re,ready;
output [31:0] exec_data_prs1_0, exec_data_prs1_1, exec_data_prs1_2, exec_data_prs1_3;
output [31:0] exec_data_prs2_0, exec_data_prs2_1, exec_data_prs2_2, exec_data_prs2_3;

output [6:0] ex_prd_0, ex_prd_1, ex_prd_2, ex_prd_3;
output [31:0] ex_imm_0, ex_imm_1, ex_imm_2, ex_imm_3;
output [6:0] ex_func7_0, ex_func7_1, ex_func7_2, ex_func7_3;
output [2:0] ex_func3_0, ex_func3_1, ex_func3_2, ex_func3_3;
output [6:0] ex_opcode_0, ex_opcode_1, ex_opcode_2, ex_opcode_3;
output [3:0] ex_has_dest, ex_is_branch, ex_is_jump, ex_is_jalr, ex_valid;
output [31:0] ex_src1_data_0, ex_src1_data_1, ex_src1_data_2, ex_src1_data_3;
output [31:0] ex_src2_data_0, ex_src2_data_1, ex_src2_data_2, ex_src2_data_3;

output [31:0] alu_result_0, alu_result_1, alu_result_2,alu_result_3;
output alu_branch_taken_0, alu_branch_taken_1, alu_branch_taken_2,alu_branch_taken_3;
output alu_valid_0, alu_valid_1, alu_valid_2,alu_valid_3;
output [6:0] alu_prd_0, alu_prd_1, alu_prd_2,alu_prd_3;
output alu_has_dest_0, alu_has_dest_1, alu_has_dest_2,alu_has_dest_3;

output [31:0] wb_result_0, wb_result_1, wb_result_2,wb_result_3;
output [6:0] wb_prd_0, wb_prd_1, wb_prd_2,wb_prd_3;
output wb_has_dest_0, wb_has_dest_1, wb_has_dest_2,wb_has_dest_3;
output wb_valid_0, wb_valid_1, wb_valid_2,wb_valid_3;
output wb_branch_taken_0, wb_branch_taken_1, wb_branch_taken_2,wb_branch_taken_3;

output wb_is_branch_0, wb_is_branch_1, wb_is_branch_2,wb_is_branch_3,alu3_stalled;

output lsq_store_ready;
output mispredicted, flush;
wire master_flush = flush | squashing;
output is_branch_out_0,is_branch_out_1,is_branch_out_2,is_branch_out_3;

wire push,pop;
wire full,empty;

wire squashing;
wire rat_restore_valid;
wire [4:0] rat_restore_rd;
wire [6:0] rat_restore_prd;
wire [6:0] rat_restore_new_prd;

wire [31:0] correct_pc;
wire [31:0] pc_fetch_0,pc_fetch_1,pc_fetch_2,pc_fetch_3; 
wire [31:0] pc_iq_0,pc_iq_1,pc_iq_2,pc_iq_3;    
wire [31:0] issue_pc_0, issue_pc_1, issue_pc_2, issue_pc_3; 
wire [31:0] ex_pc_0,ex_pc_1,ex_pc_2,ex_pc_3;    
wire [31:0] wb_pc_0,wb_pc_1,wb_pc_2,wb_pc_3;  
wire [31:0] pc_ifid_0,pc_ifid_1,pc_ifid_2,pc_ifid_3; 
wire [31:0] pc_dec_0,pc_dec_1,pc_dec_2,pc_dec_3; 
wire [31:0] pc_ren_0,   pc_ren_1,   pc_ren_2,   pc_ren_3;
wire issue_is_mul_3;

PC a(.clk(clk),
     .rst(rst),
     .next(next),
     .flush(flush),
     .correct_pc(correct_pc),
     .pc(pc),
     .hold(squashing));
     
Instruction_Mem b(.rst(rst),
                  .pc(pc),
                  .ins0(ins0),
                  .ins1(ins1),
                  .ins2(ins2),
                  .ins3(ins3));
                  
Predecode_BPL c(.pc(pc),
                .ins0(ins0),
                .ins1(ins1),
                .ins2(ins2),
                .ins3(ins3),
                .IN0(in0),
                .IN1(in1),
                .IN2(in2),
                .IN3(in3),
                .pc_out(next),
                .valid(valid),
                .pc_0(pc_fetch_0),
                .pc_1(pc_fetch_1),
                .pc_2(pc_fetch_2),
                .pc_3(pc_fetch_3));
                                
assign push = (|valid) && !full && !stall;
assign pop  = !empty && !stall;        
        
Instruction_Queue d(.clk(clk),
                    .rst(rst),
                    .ins0(in0),
                    .ins1(in1),
                    .ins2(in2),
                    .ins3(in3),
                    .valid(valid),
                    .ins0_out(in0_out),
                    .ins1_out(in1_out),
                    .ins2_out(in2_out),
                    .ins3_out(in3_out),
                    .valid_out(valid_out_iqueue),
                    .push(push),
                    .pop(pop),
                    .flush(flush),
                    .full(full),
                    .empty(empty),
                    .pc_0_in(pc_fetch_0),
                    .pc_1_in(pc_fetch_1),
                    .pc_2_in(pc_fetch_2),
                    .pc_3_in(pc_fetch_3),
                    .pc_0_out(pc_ifid_0),
                    .pc_1_out(pc_ifid_1),
                    .pc_2_out(pc_ifid_2),
                    .pc_3_out(pc_ifid_3));
                    
IF_ID P1(.clk(clk),
         .rst(rst),
         .ins0_out_F(in0_out),
         .ins1_out_F(in1_out),
         .ins2_out_F(in2_out),
         .ins3_out_F(in3_out),
         .valid_out_F(valid_out_iqueue),
         .ins0_out_D(ins0_out_D),
         .ins1_out_D(ins1_out_D),
         .ins2_out_D(ins2_out_D),
         .ins3_out_D(ins3_out_D),
         .valid_out_D(valid_out_D),
         .flush(flush),
         .pc_0_F(pc_ifid_0),
         .pc_1_F(pc_ifid_1),
         .pc_2_F(pc_ifid_2),
         .pc_3_F(pc_ifid_3),
         .pc_0_D(pc_dec_0),
         .pc_1_D(pc_dec_1),
         .pc_2_D(pc_dec_2),
         .pc_3_D(pc_dec_3));
                    
Decode e(.ins_0(ins0_out_D),
         .ins_1(ins1_out_D),
         .ins_2(ins2_out_D),
         .ins_3(ins3_out_D),
         .valid_in(valid_out_D),
         .opcode_0(opcode_0),
         .opcode_1(opcode_1),
         .opcode_2(opcode_2),
         .opcode_3(opcode_3),
         .rs1_0(rs1_0),
         .rs1_1(rs1_1),
         .rs1_2(rs1_2),
         .rs1_3(rs1_3),
         .rs2_0(rs2_0),
         .rs2_1(rs2_1),
         .rs2_2(rs2_2),
         .rs2_3(rs2_3),
         .rd_0(rd_0),
         .rd_1(rd_1),
         .rd_2(rd_2),
         .rd_3(rd_3),
         .imm_0(imm_0),
         .imm_1(imm_1),
         .imm_2(imm_2),
         .imm_3(imm_3),
         .func7_0(func7_0),
         .func7_1(func7_1),
         .func7_2(func7_2),
         .func7_3(func7_3),
         .func3_0(func3_0),
         .func3_1(func3_1),
         .func3_2(func3_2),
         .func3_3(func3_3),
         .has_dest(has_dest),
         .is_branch(is_branch),
         .is_jump(is_jump),
         .is_jalr(is_jalr),
         .is_load(is_load),
         .is_store(is_store),
         .valid_out(valid_out_decode));
              
Rename_Dispatch f(.clk(clk),
                  .rst(rst),
                  .rs1_0(rs1_0),
                  .rs1_1(rs1_1),
                  .rs1_2(rs1_2),
                  .rs1_3(rs1_3),
                  .rs2_0(rs2_0),
                  .rs2_1(rs2_1),
                  .rs2_2(rs2_2),
                  .rs2_3(rs2_3),
                  .rd_0(rd_0),
                  .rd_1(rd_1),
                  .rd_2(rd_2),
                  .rd_3(rd_3),
                  .imm_0(imm_0),
                  .imm_1(imm_1),
                  .imm_2(imm_2),
                  .imm_3(imm_3),
                  .func7_0(func7_0),
                  .func7_1(func7_1),
                  .func7_2(func7_2),
                  .func7_3(func7_3),
                  .func3_0(func3_0),
                  .func3_1(func3_1),
                  .func3_2(func3_2),
                  .func3_3(func3_3),
                  .opcode_0(opcode_0),
                  .opcode_1(opcode_1),
                  .opcode_2(opcode_2),
                  .opcode_3(opcode_3),
                  .has_dest(has_dest),
                  .is_branch(is_branch),
                  .is_jump(is_jump),
                  .is_jalr(is_jalr),
                  .is_load(is_load),
                  .is_store(is_store),
                  .valid_in(valid_out_decode),
                  .rat_rs1_0(rat_rs1_0),
                  .rat_rs1_1(rat_rs1_1),
                  .rat_rs1_2(rat_rs1_2),
                  .rat_rs1_3(rat_rs1_3),
                  .rat_rs2_0(rat_rs2_0),
                  .rat_rs2_1(rat_rs2_1),
                  .rat_rs2_2(rat_rs2_2),
                  .rat_rs2_3(rat_rs2_3),
                  .rat_rd_0(rat_rd_0),
                  .rat_rd_1(rat_rd_1),
                  .rat_rd_2(rat_rd_2),
                  .rat_rd_3(rat_rd_3),
                  .rat_prs1_0(prs1_0),
                  .rat_prs1_1(prs1_1),
                  .rat_prs1_2(prs1_2),
                  .rat_prs1_3(prs1_3),
                  .rat_prs2_0(prs2_0),
                  .rat_prs2_1(prs2_1),
                  .rat_prs2_2(prs2_2),
                  .rat_prs2_3(prs2_3),
                  .rat_old_prd_0(old_prd_0),
                  .rat_old_prd_1(old_prd_1),
                  .rat_old_prd_2(old_prd_2),
                  .rat_old_prd_3(old_prd_3),
                  .rat_update_valid(rat_update_valid),
                  .rat_new_rd_0(rat_new_rd_0),
                  .rat_new_rd_1(rat_new_rd_1),
                  .rat_new_rd_2(rat_new_rd_2),
                  .rat_new_rd_3(rat_new_rd_3),
                  .rat_new_prd_0(rat_new_prd_0),
                  .rat_new_prd_1(rat_new_prd_1),
                  .rat_new_prd_2(rat_new_prd_2),
                  .rat_new_prd_3(rat_new_prd_3),
                  .fl_alloc_req(fl_alloc_req),
                  .fl_alloc_preg_0(alloc_preg_0),
                  .fl_alloc_preg_1(alloc_preg_1),
                  .fl_alloc_preg_2(alloc_preg_2),
                  .fl_alloc_preg_3(alloc_preg_3),
                  .fl_stall(fl_stall),
                  .prs1_0(prs1_out_0),
                  .prs1_1(prs1_out_1),
                  .prs1_2(prs1_out_2),
                  .prs1_3(prs1_out_3),
                  .prs2_0(prs2_out_0),
                  .prs2_1(prs2_out_1),
                  .prs2_2(prs2_out_2),
                  .prs2_3(prs2_out_3),
                  .prd_0(prd_out_0),
                  .prd_1(prd_out_1),
                  .prd_2(prd_out_2),
                  .prd_3(prd_out_3),
                  .old_prd_0(old_prd_out_0),
                  .old_prd_1(old_prd_out_1),
                  .old_prd_2(old_prd_out_2),
                  .old_prd_3(old_prd_out_3),
                  .imm_out_0(imm_out_0),
                  .imm_out_1(imm_out_1),
                  .imm_out_2(imm_out_2),
                  .imm_out_3(imm_out_3),
                  .func7_out_0(func7_out_0),
                  .func7_out_1(func7_out_1),
                  .func7_out_2(func7_out_2),
                  .func7_out_3(func7_out_3),
                  .func3_out_0(func3_out_0),
                  .func3_out_1(func3_out_1),
                  .func3_out_2(func3_out_2),
                  .func3_out_3(func3_out_3),
                  .opcode_out_0(opcode_out_0),
                  .opcode_out_1(opcode_out_1),
                  .opcode_out_2(opcode_out_2),
                  .opcode_out_3(opcode_out_3),
                  .has_dest_out(has_dest_out),
                  .is_branch_out(is_branch_out),
                  .is_jump_out(is_jump_out),
                  .is_jalr_out(is_jalr_out),
                  .is_load_out(is_load_out),
                  .is_store_out(is_store_out),
                  .valid_out(valid_out_rename),
                  .stall(stall),
                  .iq_queue_full(queue_almost_full),
                  .rd_out_0(rd_out_0),
                  .rd_out_1(rd_out_1),
                  .rd_out_2(rd_out_2),
                  .rd_out_3(rd_out_3),
                  .rob_almost_full_in(rob_almost_full),
                  .lsq_full(lsq_full),
                  .squashing(squashing),
                  .pc_0_in(pc_dec_0), 
                  .pc_1_in(pc_dec_1), 
                  .pc_2_in(pc_dec_2), 
                  .pc_3_in(pc_dec_3),
                  .pc_0_out(pc_ren_0), 
                  .pc_1_out(pc_ren_1), 
                  .pc_2_out(pc_ren_2), 
                  .pc_3_out(pc_ren_3));

RAT g(.clk(clk),
      .rst(rst),
      .rs1_0(rat_rs1_0),
      .rs1_1(rat_rs1_1),
      .rs1_2(rat_rs1_2),
      .rs1_3(rat_rs1_3),
      .rs2_0(rat_rs2_0),
      .rs2_1(rat_rs2_1),
      .rs2_2(rat_rs2_2),
      .rs2_3(rat_rs2_3),
      .rd_0(rat_rd_0),
      .rd_1(rat_rd_1),
      .rd_2(rat_rd_2),
      .rd_3(rat_rd_3),
      .update_valid(rat_update_valid),
      .new_rd_0(rat_new_rd_0),
      .new_rd_1(rat_new_rd_1),
      .new_rd_2(rat_new_rd_2),
      .new_rd_3(rat_new_rd_3),
      .new_prd_0(rat_new_prd_0),
      .new_prd_1(rat_new_prd_1),
      .new_prd_2(rat_new_prd_2),
      .new_prd_3(rat_new_prd_3),
      .prs1_0(prs1_0),
      .prs1_1(prs1_1),
      .prs1_2(prs1_2),
      .prs1_3(prs1_3),
      .prs2_0(prs2_0),
      .prs2_1(prs2_1),
      .prs2_2(prs2_2),
      .prs2_3(prs2_3),
      .old_prd_0(old_prd_0),
      .old_prd_1(old_prd_1),
      .old_prd_2(old_prd_2),
      .old_prd_3(old_prd_3),
      .flush_valid(rat_restore_valid),
      .flush_rd(rat_restore_rd),
      .flush_prd(rat_restore_prd));

Free_List h(.clk(clk),
            .rst(rst),
            .alloc_req(fl_alloc_req),
            .alloc_preg_0(alloc_preg_0),
            .alloc_preg_1(alloc_preg_1),
            .alloc_preg_2(alloc_preg_2),
            .alloc_preg_3(alloc_preg_3),
            .stall(fl_stall),
            .rob_free_valid(rob_free_valid),
            .rob_free_preg_0(rob_free_preg_0),
            .rob_free_preg_1(rob_free_preg_1),
            .rob_free_preg_2(rob_free_preg_2),
            .rob_free_preg_3(rob_free_preg_3),
            .squash_free_valid(rat_restore_valid),
            .squash_free_preg(rat_restore_new_prd));
            
RE_IQ i(.clk(clk),
       .rst(rst),
       .prs1_0_R(prs1_out_0),
       .prs1_1_R(prs1_out_1),
       .prs1_2_R(prs1_out_2),
       .prs1_3_R(prs1_out_3),
       .prs2_0_R(prs2_out_0),
       .prs2_1_R(prs2_out_1),
       .prs2_2_R(prs2_out_2),
       .prs2_3_R(prs2_out_3),
       .prd_0_R(prd_out_0),
       .prd_1_R(prd_out_1),
       .prd_2_R(prd_out_2),
       .prd_3_R(prd_out_3),
       .old_prd_0_R(old_prd_out_0),
       .old_prd_1_R(old_prd_out_1),
       .old_prd_2_R(old_prd_out_2),
       .old_prd_3_R(old_prd_out_3),
       .imm_out_0_R(imm_out_0),
       .imm_out_1_R(imm_out_1),
       .imm_out_2_R(imm_out_2),
       .imm_out_3_R(imm_out_3),
       .func7_out_0_R(func7_out_0),
       .func7_out_1_R(func7_out_1),
       .func7_out_2_R(func7_out_2),
       .func7_out_3_R(func7_out_3),
       .func3_out_0_R(func3_out_0),
       .func3_out_1_R(func3_out_1),
       .func3_out_2_R(func3_out_2),
       .func3_out_3_R(func3_out_3),
       .opcode_out_0_R(opcode_out_0),
       .opcode_out_1_R(opcode_out_1),
       .opcode_out_2_R(opcode_out_2),
       .opcode_out_3_R(opcode_out_3),
       .has_dest_out_R(has_dest_out),
       .is_branch_out_R(is_branch_out),
       .is_jump_out_R(is_jump_out),
       .is_jalr_out_R(is_jalr_out),
       .is_load_out_R(is_load_out),
       .is_store_out_R(is_store_out),
       .valid_out_R(valid_out_rename),
       .stall_R(stall),
       .rd_0_R(rd_out_0),
       .rd_1_R(rd_out_1),
       .rd_2_R(rd_out_2),
       .rd_3_R(rd_out_3),
       .prs1_0_IQ(prs1_0_IQ),
       .prs1_1_IQ(prs1_1_IQ),
       .prs1_2_IQ(prs1_2_IQ),
       .prs1_3_IQ(prs1_3_IQ),
       .prs2_0_IQ(prs2_0_IQ),
       .prs2_1_IQ(prs2_1_IQ),
       .prs2_2_IQ(prs2_2_IQ),
       .prs2_3_IQ(prs2_3_IQ),
       .prd_0_IQ(prd_0_IQ),
       .prd_1_IQ(prd_1_IQ),
       .prd_2_IQ(prd_2_IQ),
       .prd_3_IQ(prd_3_IQ),
       .old_prd_0_IQ(old_prd_0_IQ),
       .old_prd_1_IQ(old_prd_1_IQ),
       .old_prd_2_IQ(old_prd_2_IQ),
       .old_prd_3_IQ(old_prd_3_IQ),
       .imm_0_IQ(imm_0_IQ),
       .imm_1_IQ(imm_1_IQ),
       .imm_2_IQ(imm_2_IQ),
       .imm_3_IQ(imm_3_IQ),
       .func7_0_IQ(func7_0_IQ),
       .func7_1_IQ(func7_1_IQ),
       .func7_2_IQ(func7_2_IQ),
       .func7_3_IQ(func7_3_IQ),
       .func3_0_IQ(func3_0_IQ),
       .func3_1_IQ(func3_1_IQ),
       .func3_2_IQ(func3_2_IQ),
       .func3_3_IQ(func3_3_IQ),
       .opcode_0_IQ(opcode_0_IQ),
       .opcode_1_IQ(opcode_1_IQ),
       .opcode_2_IQ(opcode_2_IQ),
       .opcode_3_IQ(opcode_3_IQ),
       .has_dest_IQ(has_dest_IQ),
       .is_branch_IQ(is_branch_IQ),
       .is_jump_IQ(is_jump_IQ),
       .is_jalr_IQ(is_jalr_IQ),
       .is_load_IQ(is_load_IQ),
       .is_store_IQ(is_store_IQ),
       .valid_IQ(valid_IQ),
       .rd_0_IQ(rd_0_IQ),
       .rd_1_IQ(rd_1_IQ),
       .rd_2_IQ(rd_2_IQ),
       .rd_3_IQ(rd_3_IQ),
       .flush(flush),
       .pc_0_R(pc_ren_0), 
       .pc_1_R(pc_ren_1), 
       .pc_2_R(pc_ren_2), 
       .pc_3_R(pc_ren_3),
       .pc_0_IQ(pc_iq_0), 
       .pc_1_IQ(pc_iq_1), 
       .pc_2_IQ(pc_iq_2), 
       .pc_3_IQ(pc_iq_3));            
            
IssueQueue j(.clk(clk),
              .rst(rst),
              .prs1_0(prs1_0_IQ), 
              .prs1_1(prs1_1_IQ), 
              .prs1_2(prs1_2_IQ), 
              .prs1_3(prs1_3_IQ),
              .prs2_0(prs2_0_IQ), 
              .prs2_1(prs2_1_IQ),
              .prs2_2(prs2_2_IQ), 
              .prs2_3(prs2_3_IQ),
              .prd_0(prd_0_IQ), 
              .prd_1(prd_1_IQ), 
              .prd_2(prd_2_IQ), 
              .prd_3(prd_3_IQ),
              .old_prd_0(old_prd_0_IQ), 
              .old_prd_1(old_prd_1_IQ), 
              .old_prd_2(old_prd_2_IQ), 
              .old_prd_3(old_prd_3_IQ),
              .imm_0(imm_0_IQ), 
              .imm_1(imm_1_IQ), 
              .imm_2(imm_2_IQ), 
              .imm_3(imm_3_IQ),
              .func7_0(func7_0_IQ), 
              .func7_1(func7_1_IQ), 
              .func7_2(func7_2_IQ), 
              .func7_3(func7_3_IQ),
              .func3_0(func3_0_IQ), 
              .func3_1(func3_1_IQ), 
              .func3_2(func3_2_IQ), 
              .func3_3(func3_3_IQ),
              .opcode_0(opcode_0_IQ), 
              .opcode_1(opcode_1_IQ), 
              .opcode_2(opcode_2_IQ), 
              .opcode_3(opcode_3_IQ),
              .has_dest_in(has_dest_IQ),
              .is_branch_in(is_branch_IQ),
              .is_jump_in(is_jump_IQ),
              .is_jalr_in(is_jalr_IQ),
              .is_load_in(is_load_IQ),
              .is_store_in(is_store_IQ),  
              .valid_in(valid_IQ),
              .prf_ready(prf_ready),
              .cdb_valid(cdb_valid[3:0]),
              .cdb_tag_0(cdb_tag_0), 
              .cdb_tag_1(cdb_tag_1), 
              .cdb_tag_2(cdb_tag_2), 
              .cdb_tag_3(cdb_tag_3),
              .issue_prs1_0(issue_prs1_0), 
              .issue_prs1_1(issue_prs1_1), 
              .issue_prs1_2(issue_prs1_2), 
              .issue_prs1_3(issue_prs1_3),
              .issue_prs2_0(issue_prs2_0), 
              .issue_prs2_1(issue_prs2_1), 
              .issue_prs2_2(issue_prs2_2), 
              .issue_prs2_3(issue_prs2_3),
              .issue_prd_0(issue_prd_0), 
              .issue_prd_1(issue_prd_1), 
              .issue_prd_2(issue_prd_2), 
              .issue_prd_3(issue_prd_3),
              .issue_old_prd_0(issue_old_prd_0), 
              .issue_old_prd_1(issue_old_prd_1), 
              .issue_old_prd_2(issue_old_prd_2), 
              .issue_old_prd_3(issue_old_prd_3),
              .issue_imm_0(issue_imm_0), 
              .issue_imm_1(issue_imm_1), 
              .issue_imm_2(issue_imm_2), 
              .issue_imm_3(issue_imm_3),
              .issue_func7_0(issue_func7_0), 
              .issue_func7_1(issue_func7_1), 
              .issue_func7_2(issue_func7_2), 
              .issue_func7_3(issue_func7_3),
              .issue_func3_0(issue_func3_0), 
              .issue_func3_1(issue_func3_1), 
              .issue_func3_2(issue_func3_2), 
              .issue_func3_3(issue_func3_3),
              .issue_opcode_0(issue_opcode_0), 
              .issue_opcode_1(issue_opcode_1), 
              .issue_opcode_2(issue_opcode_2), 
              .issue_opcode_3(issue_opcode_3),
              .issue_has_dest(issue_has_dest),
              .issue_is_branch(issue_is_branch),
              .issue_is_jump(issue_is_jump),
              .issue_is_jalr(issue_is_jalr),
              .issue_valid(issue_valid),
              .issue_is_mul_3(issue_is_mul_3),
              .queue_full(queue_full),
              .queue_almost_full(queue_almost_full),
              .flush(flush),
              .pc_0(pc_iq_0), 
              .pc_1(pc_iq_1), 
              .pc_2(pc_iq_2), 
              .pc_3(pc_iq_3),
              .issue_pc_0(issue_pc_0), 
              .issue_pc_1(issue_pc_1), 
              .issue_pc_2(issue_pc_2), 
              .issue_pc_3(issue_pc_3));

PRF k(.clk(clk),
      .rst(rst),
      .rd_prs1_0(prs1_0_IQ),
      .rd_prs1_1(prs1_1_IQ), 
      .rd_prs1_2(prs1_2_IQ), 
      .rd_prs1_3(prs1_3_IQ),
      .rd_prs2_0(prs2_0_IQ), 
      .rd_prs2_1(prs2_1_IQ), 
      .rd_prs2_2(prs2_2_IQ), 
      .rd_prs2_3(prs2_3_IQ),
      .rd_data_prs1_0(rd_data_prs1_0), 
      .rd_data_prs1_1(rd_data_prs1_1), 
      .rd_data_prs1_2(rd_data_prs1_2), 
      .rd_data_prs1_3(rd_data_prs1_3),
      .rd_data_prs2_0(rd_data_prs2_0), 
      .rd_data_prs2_1(rd_data_prs2_1), 
      .rd_data_prs2_2(rd_data_prs2_2), 
      .rd_data_prs2_3(rd_data_prs2_3),
      .alloc_valid(fl_alloc_req),
      .alloc_prd_0(alloc_preg_0), 
      .alloc_prd_1(alloc_preg_1), 
      .alloc_prd_2(alloc_preg_2), 
      .alloc_prd_3(alloc_preg_3),
      .cdb_valid(cdb_valid[3:0]),
      .cdb_tag_0(cdb_tag_0),  
      .cdb_tag_1(cdb_tag_1),  
      .cdb_tag_2(cdb_tag_2),  
      .cdb_tag_3(cdb_tag_3),
      .cdb_data_0(cdb_data_0), 
      .cdb_data_1(cdb_data_1), 
      .cdb_data_2(cdb_data_2), 
      .cdb_data_3(cdb_data_3),
      .prf_ready(prf_ready),
      .commit_prd_0(commit_prd_0),
      .commit_prd_1(commit_prd_1),
      .commit_prd_2(commit_prd_2),
      .commit_prd_3(commit_prd_3),
      .commit_data_0(commit_data_0),
      .commit_data_1(commit_data_1),
      .commit_data_2(commit_data_2),
      .commit_data_3(commit_data_3),
      .lsq_rd_prs1_0(lsq_rd_prs1_0),
      .lsq_rd_prs1_1(lsq_rd_prs1_1),
      .lsq_rd_prs1_2(lsq_rd_prs1_2),
      .lsq_rd_prs1_3(lsq_rd_prs1_3),
      .lsq_rd_prs2_0(lsq_rd_prs2_0),
      .lsq_rd_prs2_1(lsq_rd_prs2_1),
      .lsq_rd_prs2_2(lsq_rd_prs2_2),
      .lsq_rd_prs2_3(lsq_rd_prs2_3),
      .lsq_data_prs1_0(lsq_data_prs1_0),
      .lsq_data_prs1_1(lsq_data_prs1_1),
      .lsq_data_prs1_2(lsq_data_prs1_2),
      .lsq_data_prs1_3(lsq_data_prs1_3),
      .lsq_data_prs2_0(lsq_data_prs2_0),
      .lsq_data_prs2_1(lsq_data_prs2_1),
      .lsq_data_prs2_2(lsq_data_prs2_2),
      .lsq_data_prs2_3(lsq_data_prs2_3),
      .exec_rd_prs1_0(issue_prs1_0), 
      .exec_rd_prs1_1(issue_prs1_1),
      .exec_rd_prs1_2(issue_prs1_2), 
      .exec_rd_prs1_3(issue_prs1_3),
      .exec_rd_prs2_0(issue_prs2_0), 
      .exec_rd_prs2_1(issue_prs2_1),
      .exec_rd_prs2_2(issue_prs2_2), 
      .exec_rd_prs2_3(issue_prs2_3),
      .exec_data_prs1_0(exec_data_prs1_0),
      .exec_data_prs1_1(exec_data_prs1_1),
      .exec_data_prs1_2(exec_data_prs1_2),
      .exec_data_prs1_3(exec_data_prs1_3),
      .exec_data_prs2_0(exec_data_prs2_0),
      .exec_data_prs2_1(exec_data_prs2_1),
      .exec_data_prs2_2(exec_data_prs2_2),
      .exec_data_prs2_3(exec_data_prs2_3));

RRF l(.clk(clk),
      .rst(rst),
      .commit_valid(commit_valid),
      .commit_rd_0(commit_rd_0),
      .commit_rd_1(commit_rd_1),
      .commit_rd_2(commit_rd_2),
      .commit_rd_3(commit_rd_3),
      .commit_data_0(commit_data_0),
      .commit_data_1(commit_data_1),
      .commit_data_2(commit_data_2),
      .commit_data_3(commit_data_3),
      .rd_addr_0(5'd0),
      .rd_addr_1(5'd0),
      .rd_data_0(),
      .rd_data_1());
      
ROB m(.clk(clk),
      .rst(rst),
      .prd_0(prd_0_IQ),     
      .prd_1(prd_1_IQ),     
      .prd_2(prd_2_IQ),     
      .prd_3(prd_3_IQ),
      .old_prd_0(old_prd_0_IQ), 
      .old_prd_1(old_prd_1_IQ), 
      .old_prd_2(old_prd_2_IQ), 
      .old_prd_3(old_prd_3_IQ),
      .rd_0(rd_0_IQ),      
      .rd_1(rd_1_IQ),      
      .rd_2(rd_2_IQ),      
      .rd_3(rd_3_IQ),
      .has_dest_in(has_dest_IQ),
      .is_branch_in(is_branch_IQ),
      .is_jump_in(is_jump_IQ),
      .is_jalr_in(is_jalr_IQ),
      .is_load_in(is_load_IQ),
      .is_store_in(is_store_IQ),
      .valid_in(valid_IQ),
      .stall(stall),               
      .cdb_valid(cdb_valid[3:0]),
      .cdb_tag_0(cdb_tag_0), 
      .cdb_tag_1(cdb_tag_1), 
      .cdb_tag_2(cdb_tag_2), 
      .cdb_tag_3(cdb_tag_3),
      .rob_free_valid(rob_free_valid),
      .rob_free_preg_0(rob_free_preg_0),
      .rob_free_preg_1(rob_free_preg_1),
      .rob_free_preg_2(rob_free_preg_2),
      .rob_free_preg_3(rob_free_preg_3),
      .commit_valid(commit_valid),
      .commit_rd_0(commit_rd_0),
      .commit_rd_1(commit_rd_1),
      .commit_rd_2(commit_rd_2),
      .commit_rd_3(commit_rd_3),
      .commit_prd_0(commit_prd_0),
      .commit_prd_1(commit_prd_1),
      .commit_prd_2(commit_prd_2),
      .commit_prd_3(commit_prd_3),
      .rob_full(rob_full),
      .rob_almost_full(rob_almost_full),
      .rob_store_commit(rob_store_commit),
      .lsq_store_ready(lsq_store_ready),
      .flush(flush),
      .squashing(squashing),
      .rat_restore_valid(rat_restore_valid),
      .rat_restore_rd(rat_restore_rd),
      .rat_restore_prd(rat_restore_prd),
      .rat_restore_new_prd(rat_restore_new_prd));

LSQ n(.clk(clk),
      .rst(rst),
      .prs1_0(prs1_0_IQ),
      .prs1_1(prs1_1_IQ),
      .prs1_2(prs1_2_IQ),
      .prs1_3(prs1_3_IQ),
      .prs2_0(prs2_0_IQ),
      .prs2_1(prs2_1_IQ),
      .prs2_2(prs2_2_IQ),
      .prs2_3(prs2_3_IQ),
      .prd_0(prd_0_IQ),
      .prd_1(prd_1_IQ),
      .prd_2(prd_2_IQ),
      .prd_3(prd_3_IQ),
      .imm_0(imm_0_IQ),
      .imm_1(imm_1_IQ),
      .imm_2(imm_2_IQ),
      .imm_3(imm_3_IQ),
      .func3_0(func3_0_IQ),
      .func3_1(func3_1_IQ),
      .func3_2(func3_2_IQ),
      .func3_3(func3_3_IQ),
      .is_load_in(is_load_IQ),
      .is_store_in(is_store_IQ),
      .valid_in(valid_IQ),
      .prf_ready(prf_ready),
      .prs1_rd_addr_0(lsq_rd_prs1_0),
      .prs1_rd_addr_1(lsq_rd_prs1_1),
      .prs1_rd_addr_2(lsq_rd_prs1_2),
      .prs1_rd_addr_3(lsq_rd_prs1_3),
      .prs2_rd_addr_0(lsq_rd_prs2_0),
      .prs2_rd_addr_1(lsq_rd_prs2_1),
      .prs2_rd_addr_2(lsq_rd_prs2_2),
      .prs2_rd_addr_3(lsq_rd_prs2_3),
      .prs1_rd_data_0(lsq_data_prs1_0),
      .prs1_rd_data_1(lsq_data_prs1_1),
      .prs1_rd_data_2(lsq_data_prs1_2),
      .prs1_rd_data_3(lsq_data_prs1_3),
      .prs2_rd_data_0(lsq_data_prs2_0),
      .prs2_rd_data_1(lsq_data_prs2_1),
      .prs2_rd_data_2(lsq_data_prs2_2),
      .prs2_rd_data_3(lsq_data_prs2_3),
      .cdb_valid(cdb_valid[3:0]),
      .cdb_tag_0(cdb_tag_0),
      .cdb_tag_1(cdb_tag_1),
      .cdb_tag_2(cdb_tag_2),
      .cdb_tag_3(cdb_tag_3),
      .cdb_data_0(cdb_data_0),
      .cdb_data_1(cdb_data_1),
      .cdb_data_2(cdb_data_2),
      .cdb_data_3(cdb_data_3),
      .rob_store_commit(rob_store_commit),
      .lsq_cdb_valid(lsq_cdb_valid),
      .lsq_cdb_tag(lsq_cdb_tag),
      .lsq_cdb_data(lsq_cdb_data),
      .mem_addr(mem_addr),
      .mem_wdata(mem_wdata),
      .mem_we(mem_we),
      .mem_re(mem_re),
      .mem_func3(mem_func3),
      .mem_rdata(rdata),
      .mem_ready(ready),
      .lsq_full(lsq_full),
      .stall(stall),
      .lsq_store_ready(lsq_store_ready),
      .flush(flush));

Data_Memory o(.clk(clk),
              .rst(rst),
              .addr(mem_addr),
              .wdata(mem_wdata),
              .we(mem_we),
              .re(mem_re),
              .func3(mem_func3),
              .rdata(rdata),
              .ready(ready));
              
IQ_EX p(.clk(clk), 
        .rst(rst),
        .issue_prd_0(issue_prd_0),
        .issue_prd_1(issue_prd_1),
        .issue_prd_2(issue_prd_2),
        .issue_prd_3(issue_prd_3),
        .issue_imm_0(issue_imm_0), 
        .issue_imm_1(issue_imm_1),
        .issue_imm_2(issue_imm_2),
        .issue_imm_3(issue_imm_3),
        .issue_func7_0(issue_func7_0), 
        .issue_func7_1(issue_func7_1),
        .issue_func7_2(issue_func7_2),
        .issue_func7_3(issue_func7_3),
        .issue_func3_0(issue_func3_0), 
        .issue_func3_1(issue_func3_1),
        .issue_func3_2(issue_func3_2),
        .issue_func3_3(issue_func3_3),
        .issue_opcode_0(issue_opcode_0), 
        .issue_opcode_1(issue_opcode_1),
        .issue_opcode_2(issue_opcode_2),
        .issue_opcode_3(issue_opcode_3),
        .issue_has_dest(issue_has_dest),
        .issue_is_branch(issue_is_branch),
        .issue_is_jump(issue_is_jump),
        .issue_is_jalr(issue_is_jalr),
        .issue_valid(issue_valid),
        .src1_data_0(exec_data_prs1_0), 
        .src1_data_1(exec_data_prs1_1),
        .src1_data_2(exec_data_prs1_2),
        .src1_data_3(exec_data_prs1_3),   
        .src2_data_0(exec_data_prs2_0),
        .src2_data_1(exec_data_prs2_1),
        .src2_data_2(exec_data_prs2_2),
        .src2_data_3(exec_data_prs2_3),
        .ex_prd_0(ex_prd_0), 
        .ex_prd_1(ex_prd_1),
        .ex_prd_2(ex_prd_2),
        .ex_prd_3(ex_prd_3),
        .ex_imm_0(ex_imm_0),
        .ex_imm_1(ex_imm_1),
        .ex_imm_2(ex_imm_2),
        .ex_imm_3(ex_imm_3),
        .ex_func7_0(ex_func7_0),
        .ex_func7_1(ex_func7_1),
        .ex_func7_2(ex_func7_2),
        .ex_func7_3(ex_func7_3),
        .ex_func3_0(ex_func3_0),
        .ex_func3_1(ex_func3_1),
        .ex_func3_2(ex_func3_2),
        .ex_func3_3(ex_func3_3),
        .ex_opcode_0(ex_opcode_0),
        .ex_opcode_1(ex_opcode_1),
        .ex_opcode_2(ex_opcode_2),
        .ex_opcode_3(ex_opcode_3),
        .ex_has_dest(ex_has_dest),
        .ex_is_branch(ex_is_branch),
        .ex_is_jump(ex_is_jump),
        .ex_is_jalr(ex_is_jalr),
        .ex_valid(ex_valid),
        .ex_src1_data_0(ex_src1_data_0), 
        .ex_src1_data_1(ex_src1_data_1),
        .ex_src1_data_2(ex_src1_data_2),
        .ex_src1_data_3(ex_src1_data_3),
        .ex_src2_data_0(ex_src2_data_0),
        .ex_src2_data_1(ex_src2_data_1),
        .ex_src2_data_2(ex_src2_data_2),
        .ex_src2_data_3(ex_src2_data_3),
        .issue_pc_0(issue_pc_0), 
        .issue_pc_1(issue_pc_1), 
        .issue_pc_2(issue_pc_2), 
        .issue_pc_3(issue_pc_3),
        .ex_pc_0(ex_pc_0),       
        .ex_pc_1(ex_pc_1),       
        .ex_pc_2(ex_pc_2),       
        .ex_pc_3(ex_pc_3),
        .issue_is_mul_3(issue_is_mul_3),
        .ex_is_mul_3(ex_is_mul_3));

// 3 ALU instances
ALU q1(.opcode(ex_opcode_0), 
      .func3(ex_func3_0), 
      .func7(ex_func7_0),
      .src1(ex_src1_data_0), 
      .src2(ex_src2_data_0), 
      .imm(ex_imm_0),
      .valid_in(ex_valid[0]), 
      .prd_in(ex_prd_0),
      .has_dest_in(ex_has_dest[0]),
      .is_branch_in(ex_is_branch[0]),
      .is_jump_in(ex_is_jump[0]),
      .is_jalr_in(ex_is_jalr[0]),
      .result(alu_result_0), 
      .branch_taken(alu_branch_taken_0),
      .valid_out(alu_valid_0), 
      .prd_out(alu_prd_0), 
      .has_dest_out(alu_has_dest_0),
      .is_branch_out(is_branch_out_0),
      .pc_in(ex_pc_0));
      
ALU q2(.opcode(ex_opcode_1), 
      .func3(ex_func3_1), 
      .func7(ex_func7_1),
      .src1(ex_src1_data_1), 
      .src2(ex_src2_data_1), 
      .imm(ex_imm_1),
      .valid_in(ex_valid[1]), 
      .prd_in(ex_prd_1),
      .has_dest_in(ex_has_dest[1]),
      .is_branch_in(ex_is_branch[1]),
      .is_jump_in(ex_is_jump[1]),
      .is_jalr_in(ex_is_jalr[1]),
      .result(alu_result_1), 
      .branch_taken(alu_branch_taken_1),
      .valid_out(alu_valid_1), 
      .prd_out(alu_prd_1), 
      .has_dest_out(alu_has_dest_1),
      .is_branch_out(is_branch_out_1),
      .pc_in(ex_pc_1));
      
ALU q3(.opcode(ex_opcode_2), 
      .func3(ex_func3_2), 
      .func7(ex_func7_2),
      .src1(ex_src1_data_2), 
      .src2(ex_src2_data_2), 
      .imm(ex_imm_2),
      .valid_in(ex_valid[2]), 
      .prd_in(ex_prd_2),
      .has_dest_in(ex_has_dest[2]),
      .is_branch_in(ex_is_branch[2]),
      .is_jump_in(ex_is_jump[2]),
      .is_jalr_in(ex_is_jalr[2]),
      .result(alu_result_2), 
      .branch_taken(alu_branch_taken_2),
      .valid_out(alu_valid_2), 
      .prd_out(alu_prd_2), 
      .has_dest_out(alu_has_dest_2),
      .is_branch_out(is_branch_out_2),
      .pc_in(ex_pc_2));
      
// CDB and Multiplier Unit signals
wire mul_unit_valid;
wire [6:0] mul_unit_tag;
wire [31:0] mul_unit_result;
wire mul_stalled;
wire ex_is_mul_3;
wire wb_is_mul_3;

// Add in TOP:
ALU q4(.opcode(ex_opcode_3),
       .func3(ex_func3_3),
       .func7(ex_func7_3),
       .src1(ex_src1_data_3),
       .src2(ex_src2_data_3),
       .imm(ex_imm_3),
       .valid_in(ex_valid[3]),
       .prd_in(ex_prd_3),
       .has_dest_in(ex_has_dest[3]),
       .is_branch_in(ex_is_branch[3]),
       .is_jump_in(ex_is_jump[3]),
       .is_jalr_in(ex_is_jalr[3]),
       .result(alu_result_3),
       .branch_taken(alu_branch_taken_3),
       .valid_out(alu_valid_3),
       .prd_out(alu_prd_3),
       .has_dest_out(alu_has_dest_3),
       .is_branch_out(is_branch_out_3),
       .pc_in(ex_pc_3));

// same for alu1, alu2 using slots 1 and 2

// EX_WB
EX_WB r(.clk(clk),
        .rst(rst),
        .alu_result_0(alu_result_0),
        .alu_result_1(alu_result_1),
        .alu_result_2(alu_result_2),
        .alu_result_3(alu_result_3),
        .alu_prd_0(alu_prd_0),
        .alu_prd_1(alu_prd_1),
        .alu_prd_2(alu_prd_2),
        .alu_prd_3(alu_prd_3),
        .alu_has_dest_0(alu_has_dest_0),
        .alu_has_dest_1(alu_has_dest_1),
        .alu_has_dest_2(alu_has_dest_2),
        .alu_has_dest_3(alu_has_dest_3),
        .alu_valid_0(alu_valid_0),
        .alu_valid_1(alu_valid_1),
        .alu_valid_2(alu_valid_2),
        .alu_valid_3(alu_valid_3),
        .alu_is_mul_3(ex_is_mul_3),
        .wb_is_mul_3(wb_is_mul_3),
        .alu_branch_taken_0(alu_branch_taken_0),
        .alu_branch_taken_1(alu_branch_taken_1),
        .alu_branch_taken_2(alu_branch_taken_2),
        .alu_branch_taken_3(alu_branch_taken_3),
        .alu_is_branch_0(is_branch_out_0),
        .alu_is_branch_1(is_branch_out_1),
        .alu_is_branch_2(is_branch_out_2),
        .alu_is_branch_3(is_branch_out_3),
        .alu3_stalled(alu3_stalled),
        .wb_result_0(wb_result_0),
        .wb_result_1(wb_result_1),
        .wb_result_2(wb_result_2),
        .wb_result_3(wb_result_3),
        .wb_prd_0(wb_prd_0),
        .wb_prd_1(wb_prd_1),
        .wb_prd_2(wb_prd_2),
        .wb_prd_3(wb_prd_3),
        .wb_has_dest_0(wb_has_dest_0),
        .wb_has_dest_1(wb_has_dest_1),
        .wb_has_dest_2(wb_has_dest_2),
        .wb_has_dest_3(wb_has_dest_3),
        .wb_valid_0(wb_valid_0),
        .wb_valid_1(wb_valid_1),
        .wb_valid_2(wb_valid_2),
        .wb_valid_3(wb_valid_3),
        .wb_branch_taken_0(wb_branch_taken_0),
        .wb_branch_taken_1(wb_branch_taken_1),
        .wb_branch_taken_2(wb_branch_taken_2),
        .wb_branch_taken_3(wb_branch_taken_3),
        .wb_is_branch_0(wb_is_branch_0),
        .wb_is_branch_1(wb_is_branch_1),
        .wb_is_branch_2(wb_is_branch_2),
        .wb_is_branch_3(wb_is_branch_3),
        .alu_pc_0(ex_pc_0), 
        .alu_pc_1(ex_pc_1), 
        .alu_pc_2(ex_pc_2), 
        .alu_pc_3(ex_pc_3),
        .wb_pc_0(wb_pc_0),  
        .wb_pc_1(wb_pc_1),  
        .wb_pc_2(wb_pc_2),  
        .wb_pc_3(wb_pc_3));

MUL_Unit mu(
    .clk(clk),
    .rst(rst),
    .flush(flush),
    .hold(mul_stalled),
    .src1(ex_src1_data_3),
    .src2(ex_src2_data_3),
    .func3(ex_func3_3),
    .prd_in(ex_prd_3),
    .valid_in(ex_valid[3] && ex_is_mul_3),
    .prd_out(mul_unit_tag),
    .result(mul_unit_result),
    .valid_out(mul_unit_valid)
);

CDB s(.wb_valid_0(wb_valid_0),
      .wb_valid_1(wb_valid_1),
      .wb_valid_2(wb_valid_2),
      .wb_valid_3(wb_valid_3),
      .wb_prd_0(wb_prd_0),
      .wb_prd_1(wb_prd_1),
      .wb_prd_2(wb_prd_2),
      .wb_prd_3(wb_prd_3),
      .wb_result_0(wb_result_0),
      .wb_result_1(wb_result_1),
      .wb_result_2(wb_result_2),
      .wb_result_3(wb_result_3),
      .wb_has_dest_0(wb_has_dest_0),
      .wb_has_dest_1(wb_has_dest_1),
      .wb_has_dest_2(wb_has_dest_2),
      .wb_has_dest_3(wb_has_dest_3),
      .lsq_cdb_valid(lsq_cdb_valid),
      .lsq_cdb_tag(lsq_cdb_tag),
      .lsq_cdb_data(lsq_cdb_data),
      .cdb_valid(cdb_valid[3:0]),
      .cdb_tag_0(cdb_tag_0),
      .cdb_tag_1(cdb_tag_1),
      .cdb_tag_2(cdb_tag_2),
      .cdb_tag_3(cdb_tag_3),
      .cdb_data_0(cdb_data_0),
      .cdb_data_1(cdb_data_1),
      .cdb_data_2(cdb_data_2),
      .cdb_data_3(cdb_data_3),
      .wb_is_mul_3(wb_is_mul_3),
      .alu3_stalled(alu3_stalled),
      .mul_valid(mul_unit_valid),
      .mul_tag(mul_unit_tag),
      .mul_data(mul_unit_result),
      .mul_stalled(mul_stalled));
// BPU
BPU t(.clk(clk),
      .rst(rst),
      .wb_valid_0(wb_valid_0),
      .wb_valid_1(wb_valid_1),
      .wb_valid_2(wb_valid_2),
      .wb_valid_3(wb_valid_3),
      .wb_is_branch_0(wb_is_branch_0),
      .wb_is_branch_1(wb_is_branch_1),
      .wb_is_branch_2(wb_is_branch_2),
      .wb_is_branch_3(wb_is_branch_3),
      .wb_branch_taken_0(wb_branch_taken_0),
      .wb_branch_taken_1(wb_branch_taken_1),
      .wb_branch_taken_2(wb_branch_taken_2),
      .wb_branch_taken_3(wb_branch_taken_3),
      .predicted_taken(1'b1),
      .mispredicted(mispredicted),
      .flush(flush),
      .wb_pc_0(wb_pc_0), 
      .wb_pc_1(wb_pc_1), 
      .wb_pc_2(wb_pc_2), 
      .wb_pc_3(wb_pc_3),
      .correct_pc(correct_pc));
      

// Waveform generation for GTKWave
initial begin
    $dumpfile("processor_waves.vcd");
    $dumpvars(0, TOP);
end

endmodule

